name: C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-ubuntu-gcc-warnings:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install g++
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt-get install g++-10
    - name: compile
      run: |
        cd cpp
        find . -name *.cpp -print0 | xargs -n1 -0 g++-10 -Wall -Wextra -std=c++20

  build-ubuntu-gcc-analyzer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install g++
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt-get install g++-10
    - name: compile
      run: |
        cd cpp
        find . -name *.cpp -print0 | xargs -n1 -0 g++-10 -fanalyzer -Wno-analyzer-null-dereference -std=c++20

  build-ubuntu-gcc-7-warnings:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install g++-7
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt-get install g++-7
    - name: compile
      run: |
        cd cpp
        find . -name *.cpp -print0 | xargs -n1 -0 g++-7 -Wall -Wextra -std=c++17

  build-ubuntu-clang:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install clang
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-key adv --fetch-keys https://apt.llvm.org/llvm-snapshot.gpg.key
        sudo add-apt-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main"
        sudo apt-get update
        sudo apt-get install clang-10
        sudo apt-get install g++-10
    - name: compile
      run: |
        cd cpp
        find . -name *.cpp -print0 | xargs -n1 -0 clang++-10 -Wall -Wextra -std=c++20
  
