name: Java CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - {java-version: 1.8, os: ubuntu-latest}
          - {java-version: 16, os: ubuntu-latest}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.config.java-version }}
      - name: Build with Ant
        run: |
          cd java
          ant -noinput -buildfile build.xml
