name: Rust CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-ubuntu-rustc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install rustc
        run: |
          sudo apt install rustc
      - name: compile
        run: |
          cd cpp/src
          find . -name '*.rs' -print0 | xargs -n1 -0 rustc
