name: Rust CI

on: [push]

jobs:
  build-ubuntu-rustc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install rustc
        run: |
          sudo apt install rustc
      - name: format
        run: |
          cd rust
          cargo fmt -- --check
      - name: compile
        run: |
          cd rust
          cargo test
